name: carla
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-image
  - matplotlib
  - pillow
  - imageio
  - tqdm
  - pip
  - pytorch
  - torchvision
  - tensorflow=2.12
  - keras
  - opencv
  
  - pip:
      - lmdb
      - gym
      - ray
      - pygame
      - tensorboard
      - protobuf>=3.20
      - torch
      - dask
      - shapely
      - tensorboardx
      - terminaltables
      - requests
      - redis
      - atari-py
      - cvxpy
      - pyopengl
      - imgaug
      - loguru
      - scikit-learn
      
